export const styles = (theme) => ({
  infostep: {
    display: "flex",
    alignItems: "center",
    paddingTop: 85,
    paddingLeft: 150,
    "& .firststep": {
      fontWeight: "normal",
      textAlign: "center",
      color: "black",
      width: 114,
      backgroundColor: "#E5E5E5",
      height: 3,
      marginTop: "10",
      "& .firststepcirclecustom": {
        backgroundColor: "#F47B6B",
        width: 35,
        height: 35,
        borderRadius: 15,
        color: "white",
        paddingTop: 5,
        marginTop: -17,
      },
      "& .firststepcirclecustomblank": {
        backgroundColor: "#E5E5E5",
        width: 35,
        height: 35,
        borderRadius: 15,
        color: "white",
        paddingTop: 5,
        marginTop: -17,
      },
      "& .firststeptext": {
        fontSize: 13,
        color: "#E5E5E5",
      },
      "& .firststeptextcolor": {
        fontSize: 13,
        color: "#F47B6B",
      },
    },
    "& .secondstep": {
      fontWeight: "normal",
      textAlign: "center",
      color: "black",
      width: 129,
      height: 3,
      marginTop: "10",
      backgroundColor: "#E5E5E5",

      "& .secondstepcirclecustom": {
        backgroundColor: "#F47B6B",
        width: 35,
        height: 35,
        borderRadius: 15,
        color: "white",
        paddingTop: 5,
        marginTop: -17,
      },
      "& .secondstepcirclecustomblank": {
        backgroundColor: "#E5E5E5",
        width: 35,
        height: 35,
        borderRadius: 15,
        color: "white",
        paddingTop: 5,
        marginTop: -17,
      },
      "& .secondsteptext": {
        fontSize: 13,
        color: "#E5E5E5",
      },
      "& .secondsteptextcolor": {
        fontSize: 13,
        color: "#F47B6B",
      },
    },
    "& .thirdstep": {
      fontWeight: "normal",
      textAlign: "center",
      color: "black",
      width: 100,
      height: 3,
      marginTop: "10",

      "& .thirdstepcirclecustom": {
        backgroundColor: "#22AF47",
        width: 35,
        height: 35,
        borderRadius: 15,
        color: "white",
        paddingTop: 5,
        marginTop: -17,
      },
      "& .thirdstepcirclecustomblank": {
        backgroundColor: "#E5E5E5",
        width: 35,
        height: 35,
        borderRadius: 15,
        color: "white",
        paddingTop: 5,
        marginTop: -17,
      },
      "& .thirdsteptext": {
        fontSize: 13,
        color: "#E5E5E5",
      },
      "& .thirdsteptextcolor": {
        fontSize: 13,
        color: "#22AF47",
      },
    },
  },
  //   mainwrapperlist: {
  //     display: "flex",
  //     flexDirection: "column",
  //     alignItems: "center",
  //     "& .buttonlist": {
  //       padding: 10,
  //       margin: "2%",
  //     },
  //   },
});
